# -*- coding: utf-8 -*-
"""Practice - apparel

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14M8uUJ40QTIlQMCN6VIY0xOUFWXv87On

Made for the Analytics Vidhya practice problem: https://datahack.analyticsvidhya.com/contest/practice-problem-identify-the-apparels/
"""

!curl -s https://course.fast.ai/setup/colab | bash
from fastai.vision import *
from fastai.callbacks.hooks import *

pwd

from google.colab import files
files.upload()

import zipfile
zip_ref = zipfile.ZipFile('train_LbELtWX.zip', 'r')
zip_ref.extractall('')
zip_ref.close()
zip_ref = zipfile.ZipFile('test_ScVgIM0.zip', 'r')
zip_ref.extractall('')
zip_ref.close()

import os
path = Path(os.getcwd())

print(path)

df = pd.read_csv(path/'train.csv', header='infer')
df.head()

tfms = get_transforms(do_flip = True, flip_vert = False, max_rotate = 0, max_zoom = 1, max_lighting = None, max_warp = 0.0, p_affine = 0.0, p_lighting = 0.0)
print(tfms)

path = path/'train'
print(path)

data = ImageDataBunch.from_df(path, df, ds_tfms=tfms, size=28, suffix='.png')

data.show_batch(rows=5, figsize=(6,10))

learn = create_cnn (data, models.resnet50, metrics=error_rate)

learn.fit_one_cycle(8)

learn.save('F')

learn.lr_find()
learn.recorder.plot()

learn.unfreeze()
learn.fit_one_cycle(8, max_lr=slice(2e-06,1.5e-05))

learn.save(Path(os.getcwd())/'F-unfrozen', return_path=True)

learn.export(Path(os.getcwd())/'F-unfrozen.pkl')



"""Begin inference and file writing"""

img = open_image(os.getcwd()+'/test/'+'60007'+'.png')
img

print(learn.predict(img)[0])

import csv
with open('submission.csv', mode='w') as file:
  writer = csv.writer(file, delimiter=',', quotechar='"', quoting=csv.QUOTE_MINIMAL)
  writer.writerow(['id', 'label'])

  input = pd.read_csv('test.csv', header='infer')
  for index,row in input.iterrows():
    imageId = (row['id'])
    img = open_image(os.getcwd()+'/test/'+str(imageId)+'.png')
    pred_class = learn.predict(img)[0]
    writer.writerow([imageId,pred_class])
file.close()

